#!/bin/bash
set -x
export NLTK_DATA=$OPENSHIFT_DATA_DIR
echo "YOU ARE IN PRE_START HOOK"
echo $NLTK_DATA
. $VIRTUAL_ENV/bin/activate
curl https://raw.github.com/sloria/TextBlob/master/download_corpora.py | python